spring.application.name=notification-service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=edunex.22cse@gmail.com
spring.mail.password=lfkzzpbdwpaylzxg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
