spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notificationdb
    driver-class-name: org.postgresql.Driver
    username: notification
    password: notification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: mailhog
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

kafka:
  bootstrap-servers: kafka:9092

app:
  storage:
    pdf-dir: ./generated-pdfs

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework: INFO
